name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Check if PR is from Dependabot
      - name: Verify PR author is Dependabot
        id: check_author
        run: |
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "DEPENDABOT=dependabot[bot]" >> $GITHUB_ENV

      # Merge the PR if it's from Dependabot and meets branch protection rules
      - name: Auto-merge Dependabot PR
        if: env.PR_AUTHOR == env.DEPENDABOT
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
