name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      # Verify PR author is Dependabot
      - name: Verify PR author is Dependabot
        id: check_author
        run: |
          echo "::set-output name=pr_author::${{ github.event.pull_request.user.login }}"
          echo "::set-output name=dependabot::dependabot[bot]"

      # Auto-merge Dependabot PR
      - name: Auto-merge Dependabot PR
        if: steps.check_author.outputs.pr_author == steps.check_author.outputs.dependabot
        run: |
          if ! gh pr merge ${{ github.event.pull_request.number }} --merge --admin; then
            echo "Failed to merge PR. Check permissions or branch protection rules."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
